language: ruby

script: bundle exec rake spec SPEC_OPTS='--format documentation'

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - PUPPET_VERSION="3.0"
  - PUPPET_VERSION="3.1"
  - PUPPET_VERSION="3.2"
  - PUPPET_VERSION="3.3"
  - PUPPET_VERSION="3.4"
  - PUPPET_VERSION="3.5"
  - PUPPET_VERSION="3.6"
  - PUPPET_VERSION="3.6.1"

